SELECT A.INGREDIENT_TYPE, SUM(B.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO A JOIN (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF) B
ON A.FLAVOR = B.FLAVOR #A와 B의 FLAVOR가 같은 것만
GROUP BY INGREDIENT_TYPE
ORDER BY SUM(TOTAL_ORDER)